### ISSUE TITLE
zed_wrapper launch fails

### ISSUE THREAD

**Issue by PallottaEnrico** [stereolabs/zed-ros2-wrapper#125]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I'm using the zed 2 on an Nvidia Jetson xavier NX with jetpack 5.0 , i've followed the SDK installation and built zed-ros2-wrapper with Ros2 Foxy.
When launching the zed_wrapper it fails with the error code below.

### Steps to Reproduce

ros2 launch zed_wrapper zed2.launch.py

### Expected Result

zed_wrapper node correctly launched and working

### Actual Result

[INFO] [launch]: All log files can be found below /home/ubm/.ros/log/2022-12-09-16-56-44-629773-f1tenth-31297
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:226> exception=TypeError("Allowed value types are bytes, bool, int, float, str, Sequence[bool], Sequence[int], Sequence[float], Sequence[str]. Got <class 'NoneType'>.If the parameter is meant to be a string, try wrapping it in launch_ros.parameter_descriptions.ParameterValue(value, value_type=str)")>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  [Previous line repeated 4 more times]
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/node.py", line 444, in execute
    self._perform_substitutions(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/node.py", line 399, in _perform_substitutions
    evaluated_parameters = evaluate_parameters(context, self.__parameters)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/utilities/evaluate_parameters.py", line 160, in evaluate_parameters
    output_params.append(evaluate_parameter_dict(context, param))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/utilities/evaluate_parameters.py", line 95, in evaluate_parameter_dict
    raise TypeError(
TypeError: Allowed value types are bytes, bool, int, float, str, Sequence[bool], Sequence[int], Sequence[float], Sequence[str]. Got <class 'NoneType'>.If the parameter is meant to be a string, try wrapping it in launch_ros.parameter_descriptions.ParameterValue(value, value_type=str)
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:226> exception=RuntimeError('Signal event received before subprocess transport available.')>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/opaque_function.py", line 75, in execute
    return self.__function(context, *self.__args, **self.__kwargs)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/execute_process.py", line 443, in __on_signal_process_event
    raise RuntimeError('Signal event received before subprocess transport available.')
RuntimeError: Signal event received before subprocess transport available.
[INFO] [robot_state_publisher-1]: process started with pid [31300]
[robot_state_publisher-1] Parsing robot urdf xml string.
[robot_state_publisher-1] Link zed2_base_link had 1 children
[robot_state_publisher-1] Link zed2_camera_center had 4 children
[robot_state_publisher-1] Link zed2_baro_link had 0 children
[robot_state_publisher-1] Link zed2_left_camera_frame had 2 children
[robot_state_publisher-1] Link zed2_left_camera_optical_frame had 0 children
[robot_state_publisher-1] Link zed2_temp_left_link had 0 children
[robot_state_publisher-1] Link zed2_mag_link had 0 children
[robot_state_publisher-1] Link zed2_right_camera_frame had 2 children
[robot_state_publisher-1] Link zed2_right_camera_optical_frame had 0 children
[robot_state_publisher-1] Link zed2_temp_right_link had 0 children
[robot_state_publisher-1] 1670601405.559780102 [zed2.zed_state_publisher] [INFO] got segment base_link
[robot_state_publisher-1] 1670601405.560163598 [zed2.zed_state_publisher] [INFO] got segment zed2_baro_link
[robot_state_publisher-1] 1670601405.560227824 [zed2.zed_state_publisher] [INFO] got segment zed2_base_link
[robot_state_publisher-1] 1670601405.560273137 [zed2.zed_state_publisher] [INFO] got segment zed2_camera_center
[robot_state_publisher-1] 1670601405.560314897 [zed2.zed_state_publisher] [INFO] got segment zed2_left_camera_frame
[robot_state_publisher-1] 1670601405.560356914 [zed2.zed_state_publisher] [INFO] got segment zed2_left_camera_optical_frame
[robot_state_publisher-1] 1670601405.560398547 [zed2.zed_state_publisher] [INFO] got segment zed2_mag_link
[robot_state_publisher-1] 1670601405.560480149 [zed2.zed_state_publisher] [INFO] got segment zed2_right_camera_frame
[robot_state_publisher-1] 1670601405.560554583 [zed2.zed_state_publisher] [INFO] got segment zed2_right_camera_optical_frame
[robot_state_publisher-1] 1670601405.560600056 [zed2.zed_state_publisher] [INFO] got segment zed2_temp_left_link
[robot_state_publisher-1] 1670601405.560671033 [zed2.zed_state_publisher] [INFO] got segment zed2_temp_right_link
[ERROR] [robot_state_publisher-1]: process[robot_state_publisher-1] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [robot_state_publisher-1]: sending signal 'SIGTERM' to process[robot_state_publisher-1]
[ERROR] [robot_state_publisher-1]: process has died [pid 31300, exit code -15, cmd '/opt/ros/foxy/lib/robot_state_publisher/robot_state_publisher --ros-args -r __node:=zed_state_publisher -r __ns:=/zed2 --params-file /tmp/launch_params_g3hxm877'].

### ZED Camera model

ZED2

### Environment

```shell
OS : Ubuntu 20.04
GPU : Nvidia Jetson Xavier NX
ZED SKD version : v.3.8.2
ROS version : Ros2 Foxy
```

**Comment by Myzhar** [comment]
Hi @PallottaEnrico 
can I ask you to try to add this parameter to the launch command line?
`svo_path:='Live'`

**Comment by PallottaEnrico** [comment]
I've added that parameter, it still gives an error, this is the output:

ros2 launch zed_wrapper zed2.launch.py svo_path:='Live'
[INFO] [launch]: All log files can be found below /home/ubm/.ros/log/2022-12-09-17-30-43-358059-f1tenth-33457
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_state_publisher-1]: process started with pid [33461]
[INFO] [zed_wrapper-2]: process started with pid [33463]
[robot_state_publisher-1] Parsing robot urdf xml string.
[robot_state_publisher-1] Link zed2_base_link had 1 children
[robot_state_publisher-1] Link zed2_camera_center had 4 children
[robot_state_publisher-1] Link zed2_baro_link had 0 children
[robot_state_publisher-1] Link zed2_left_camera_frame had 2 children
[robot_state_publisher-1] Link zed2_left_camera_optical_frame had 0 children
[robot_state_publisher-1] Link zed2_temp_left_link had 0 children
[robot_state_publisher-1] Link zed2_mag_link had 0 children
[robot_state_publisher-1] Link zed2_right_camera_frame had 2 children
[robot_state_publisher-1] Link zed2_right_camera_optical_frame had 0 children
[robot_state_publisher-1] Link zed2_temp_right_link had 0 children
[robot_state_publisher-1] 1670603444.212782089 [zed2.zed_state_publisher] [INFO] got segment base_link
[robot_state_publisher-1] 1670603444.213084273 [zed2.zed_state_publisher] [INFO] got segment zed2_baro_link
[robot_state_publisher-1] 1670603444.213145010 [zed2.zed_state_publisher] [INFO] got segment zed2_base_link
[robot_state_publisher-1] 1670603444.213193107 [zed2.zed_state_publisher] [INFO] got segment zed2_camera_center
[robot_state_publisher-1] 1670603444.213234932 [zed2.zed_state_publisher] [INFO] got segment zed2_left_camera_frame
[robot_state_publisher-1] 1670603444.213311414 [zed2.zed_state_publisher] [INFO] got segment zed2_left_camera_optical_frame
[robot_state_publisher-1] 1670603444.213372728 [zed2.zed_state_publisher] [INFO] got segment zed2_mag_link
[robot_state_publisher-1] 1670603444.213447513 [zed2.zed_state_publisher] [INFO] got segment zed2_right_camera_frame
[robot_state_publisher-1] 1670603444.213521083 [zed2.zed_state_publisher] [INFO] got segment zed2_right_camera_optical_frame
[robot_state_publisher-1] 1670603444.213566140 [zed2.zed_state_publisher] [INFO] got segment zed2_temp_left_link
[robot_state_publisher-1] 1670603444.213606141 [zed2.zed_state_publisher] [INFO] got segment zed2_temp_right_link
[zed_wrapper-2] 1670603444.330255256 [zed2.zed_node] [INFO] ********************************
[zed_wrapper-2] 1670603444.330837543 [zed2.zed_node] [INFO]       ZED Camera Component
[zed_wrapper-2] 1670603444.330938921 [zed2.zed_node] [INFO] ********************************
[zed_wrapper-2] 1670603444.330997962 [zed2.zed_node] [INFO]  * namespace: /zed2
[zed_wrapper-2] 1670603444.331043660 [zed2.zed_node] [INFO]  * node name: zed_node
[zed_wrapper-2] 1670603444.331116397 [zed2.zed_node] [INFO] ********************************
[zed_wrapper-2] 1670603444.331220144 [zed2.zed_node] [INFO] *** DEBUG parameters ***
[zed_wrapper-2] 1670603444.331352499 [zed2.zed_node] [INFO]  * Debug mode: FALSE
[zed_wrapper-2] 1670603444.331463254 [zed2.zed_node] [INFO]  * Debug sensors: FALSE
[zed_wrapper-2] 1670603444.331558296 [zed2.zed_node] [INFO] *** GENERAL parameters ***
[zed_wrapper-2] 1670603444.331854111 [zed2.zed_node] [INFO]  * Camera model: zed2 - ZED 2
[zed_wrapper-2] 1670603444.332030596 [zed2.zed_node] [INFO]  * SDK Verbose: 1
[zed_wrapper-2] 1670603444.332134726 [zed2.zed_node] [INFO]  * SVO: Live
[zed_wrapper-2] 1670603444.332218664 [zed2.zed_node] [INFO]  * SVO Loop: FALSE
[zed_wrapper-2] 1670603444.332297546 [zed2.zed_node] [INFO]  * SVO Realtime: TRUE
[zed_wrapper-2] 1670603444.332407021 [zed2.zed_node] [INFO]  * Camera name: zed2
[zed_wrapper-2] 1670603444.332498095 [zed2.zed_node] [INFO]  * Camera ID: 0
[zed_wrapper-2] 1670603444.332649715 [zed2.zed_node] [INFO]  * Camera SN: 0
[zed_wrapper-2] 1670603444.332775798 [zed2.zed_node] [INFO]  * Camera timeout [sec]: 5
[zed_wrapper-2] 1670603444.332900601 [zed2.zed_node] [INFO]  * Camera reconnection temptatives: 5
[zed_wrapper-2] 1670603444.332996731 [zed2.zed_node] [INFO]  * Camera framerate: 60
[zed_wrapper-2] 1670603444.333081245 [zed2.zed_node] [INFO]  * GPU ID: -1
[zed_wrapper-2] 1670603444.333178688 [zed2.zed_node] [INFO]  * Camera resolution: 2 - HD720
[zed_wrapper-2] 1670603444.333346116 [zed2.zed_node] [INFO]  * Region of interest:
[zed_wrapper-2] 1670603444.333467271 [zed2.zed_node] [INFO]  * Camera self calibration: TRUE
[zed_wrapper-2] 1670603444.333581257 [zed2.zed_node] [INFO]  * Camera flip: FALSE
[zed_wrapper-2] 1670603444.333740365 [zed2.zed_node] [INFO]  * [DYN] Publish framerate [Hz]:  60
[zed_wrapper-2] 1670603444.333802063 [zed2.zed_node] [INFO] *** VIDEO parameters ***
[zed_wrapper-2] 1670603444.333912594 [zed2.zed_node] [INFO]  * Use old extrinsic parameters: 0
[zed_wrapper-2] 1670603444.333995156 [zed2.zed_node] [INFO]  * [DYN] Image downsample factor: 1
[zed_wrapper-2] 1670603444.334092854 [zed2.zed_node] [INFO]  * [DYN] Brightness: 4
[zed_wrapper-2] 1670603444.334175608 [zed2.zed_node] [INFO]  * [DYN] Contrast: 4
[zed_wrapper-2] 1670603444.334298075 [zed2.zed_node] [INFO]  * [DYN] Hue: 0
[zed_wrapper-2] 1670603444.334407902 [zed2.zed_node] [INFO]  * [DYN] Saturation: 4
[zed_wrapper-2] 1670603444.334522080 [zed2.zed_node] [INFO]  * [DYN] Sharpness: 4
[zed_wrapper-2] 1670603444.334601122 [zed2.zed_node] [INFO]  * [DYN] Gamma: 8
[zed_wrapper-2] 1670603444.334686852 [zed2.zed_node] [INFO]  * [DYN] Auto Exposure/Gain: TRUE
[zed_wrapper-2] 1670603444.334791175 [zed2.zed_node] [INFO]  * [DYN] Exposure: 80
[zed_wrapper-2] 1670603444.334872713 [zed2.zed_node] [INFO]  * [DYN] Gain: 80
[zed_wrapper-2] 1670603444.334949227 [zed2.zed_node] [INFO]  * [DYN] Auto White Balance: TRUE
[zed_wrapper-2] 1670603444.335061070 [zed2.zed_node] [INFO]  * [DYN] White Balance Temperature: 42
[zed_wrapper-2] 1670603444.335203473 [zed2.zed_node] [INFO]  * Video QoS History: KEEP_LAST
[zed_wrapper-2] 1670603444.335324084 [zed2.zed_node] [INFO]  * Video QoS History depth: 1
[zed_wrapper-2] 1670603444.335419510 [zed2.zed_node] [INFO]  * Video QoS Reliability: RELIABLE
[zed_wrapper-2] 1670603444.335509848 [zed2.zed_node] [INFO]  * Video QoS Durability: VOLATILE
[zed_wrapper-2] 1670603444.335575450 [zed2.zed_node] [INFO] *** DEPTH parameters ***
[zed_wrapper-2] 1670603444.335925347 [zed2.zed_node] [INFO]  * Depth quality: 3 - ULTRA
[zed_wrapper-2] 1670603444.336041285 [zed2.zed_node] [INFO]  * Depth downsample factor: 1
[zed_wrapper-2] 1670603444.336187433 [zed2.zed_node] [INFO]  * Min depth [m]: 0.2
[zed_wrapper-2] 1670603444.336318828 [zed2.zed_node] [INFO]  * Max depth [m]: 20
[zed_wrapper-2] 1670603444.336447983 [zed2.zed_node] [INFO]  * Depth Sensing Mode: 0 - STANDARD
[zed_wrapper-2] 1670603444.336555762 [zed2.zed_node] [INFO]  * Depth Stabilization: TRUE
[zed_wrapper-2] 1670603444.336633908 [zed2.zed_node] [INFO]  * OpenNI mode (16bit point cloud): FALSE
[zed_wrapper-2] 1670603444.336724790 [zed2.zed_node] [INFO]  * [DYN] Point cloud rate [Hz]: 10
[zed_wrapper-2] 1670603444.336810232 [zed2.zed_node] [INFO]  * [DYN] Depth Confidence: 50
[zed_wrapper-2] 1670603444.336916123 [zed2.zed_node] [INFO]  * [DYN] Depth Texture Confidence: 100
[zed_wrapper-2] 1670603444.336999741 [zed2.zed_node] [INFO]  * [DYN] Remove saturated areas: TRUE
[zed_wrapper-2] 1670603444.337106527 [zed2.zed_node] [INFO]  * Depth QoS History: KEEP_LAST
[zed_wrapper-2] 1670603444.337413127 [zed2.zed_node] [INFO]  * Depth QoS History depth: 1
[zed_wrapper-2] 1670603444.337518665 [zed2.zed_node] [INFO]  * Depth QoS Reliability: RELIABLE
[zed_wrapper-2] 1670603444.337596395 [zed2.zed_node] [INFO]  * Depth QoS Durability: VOLATILE
[zed_wrapper-2] 1670603444.337651501 [zed2.zed_node] [INFO] *** POSITIONAL TRACKING parameters ***
[zed_wrapper-2] 1670603444.337733935 [zed2.zed_node] [INFO]  * Positional tracking enabled: TRUE
[zed_wrapper-2] 1670603444.337834705 [zed2.zed_node] [INFO]  * Base frame id: base_link
[zed_wrapper-2] 1670603444.337943796 [zed2.zed_node] [INFO]  * Map frame id: map
[zed_wrapper-2] 1670603444.338061655 [zed2.zed_node] [INFO]  * Odometry frame id: odom
[zed_wrapper-2] 1670603444.338179706 [zed2.zed_node] [INFO]  * Broadcast Odometry TF: TRUE
[zed_wrapper-2] 1670603444.338317853 [zed2.zed_node] [INFO]  * Broadcast Pose TF: TRUE
[zed_wrapper-2] 1670603444.338427488 [zed2.zed_node] [INFO]  * Broadcast Static IMU TF [not for ZED]: TRUE
[zed_wrapper-2] 1670603444.338523938 [zed2.zed_node] [INFO]  * [DYN] Depth minimum range: 0
[zed_wrapper-2] 1670603444.338613092 [zed2.zed_node] [INFO]  * [DYN] TF timestamp offset: 0
[zed_wrapper-2] 1670603444.338700998 [zed2.zed_node] [INFO]  * [DYN] Path publishing rate: 2
[zed_wrapper-2] 1670603444.338804361 [zed2.zed_node] [INFO]  * Path history lenght: -1
[zed_wrapper-2] 1670603444.338941900 [zed2.zed_node] [INFO]  * Initial pose: [0,0,0,0,0,0,]
[zed_wrapper-2] 1670603444.339050255 [zed2.zed_node] [INFO]  * Area Memory: TRUE
[zed_wrapper-2] 1670603444.339136273 [zed2.zed_node] [INFO]  * Area Memory DB:
[zed_wrapper-2] 1670603444.339239251 [zed2.zed_node] [INFO]  * Camera is static: FALSE
[zed_wrapper-2] 1670603444.339331702 [zed2.zed_node] [INFO]  * Gravity as origin [not for ZED]: FALSE
[zed_wrapper-2] 1670603444.339426264 [zed2.zed_node] [INFO]  * IMU Fusion [not for ZED]: TRUE
[zed_wrapper-2] 1670603444.339523642 [zed2.zed_node] [INFO]  * Floor Alignment: FALSE
[zed_wrapper-2] 1670603444.339756736 [zed2.zed_node] [INFO]  * Init Odometry with first valid pose data: TRUE
[zed_wrapper-2] 1670603444.339879971 [zed2.zed_node] [INFO]  * 2D mode: FALSE
[zed_wrapper-2] 1670603444.339968869 [zed2.zed_node] [INFO]  * Pose/Odometry QoS History: KEEP_LAST
[zed_wrapper-2] 1670603444.340047495 [zed2.zed_node] [INFO]  * Pose/Odometry QoS History depth: 1
[zed_wrapper-2] 1670603444.340151018 [zed2.zed_node] [INFO]  * Pose/Odometry QoS Reliability: RELIABLE
[zed_wrapper-2] 1670603444.340231404 [zed2.zed_node] [INFO]  * Pose/Odometry QoS Durability: VOLATILE
[zed_wrapper-2] 1670603444.340287053 [zed2.zed_node] [INFO] *** SENSORS STACK parameters ***
[zed_wrapper-2] 1670603444.340381071 [zed2.zed_node] [INFO]  * Sensors Camera Sync: FALSE
[zed_wrapper-2] 1670603444.340532371 [zed2.zed_node] [INFO]  * Sensors publishing rate: 100 Hz
[zed_wrapper-2] 1670603444.340632117 [zed2.zed_node] [INFO]  * Sensors QoS History: KEEP_LAST
[zed_wrapper-2] 1670603444.340708663 [zed2.zed_node] [INFO]  * Sensors QoS History depth: 1
[zed_wrapper-2] 1670603444.340798841 [zed2.zed_node] [INFO]  * Sensors QoS Reliability: RELIABLE
[zed_wrapper-2] 1670603444.340874395 [zed2.zed_node] [INFO]  * Sensors QoS Durability: VOLATILE
[zed_wrapper-2] 1670603444.340927356 [zed2.zed_node] [INFO] *** Spatial Mapping parameters ***
[zed_wrapper-2] 1670603444.341024831 [zed2.zed_node] [INFO]  * Spatial Mapping Enabled: FALSE
[zed_wrapper-2] 1670603444.341160898 [zed2.zed_node] [INFO]  * Spatial Mapping resolution [m]: 0.1
[zed_wrapper-2] 1670603444.341281509 [zed2.zed_node] [INFO]  * 3D Max Mapping range [m]: 20
[zed_wrapper-2] 1670603444.341406568 [zed2.zed_node] [INFO]  * Map publishing rate [Hz]: 0.5
[zed_wrapper-2] 1670603444.341516395 [zed2.zed_node] [INFO]  * Clicked point topic: /clicked_point
[zed_wrapper-2] 1670603444.341595629 [zed2.zed_node] [INFO]  * Sensors QoS History: KEEP_LAST
[zed_wrapper-2] 1670603444.341668847 [zed2.zed_node] [INFO]  * Sensors QoS History depth: 1
[zed_wrapper-2] 1670603444.341804274 [zed2.zed_node] [INFO]  * Sensors QoS Reliability: RELIABLE
[zed_wrapper-2] 1670603444.341914709 [zed2.zed_node] [INFO]  * Sensors QoS Durability: VOLATILE
[zed_wrapper-2] 1670603444.341972950 [zed2.zed_node] [INFO] *** OBJECT DETECTION parameters ***
[zed_wrapper-2] 1670603444.342078073 [zed2.zed_node] [INFO]  * Object Detection enabled: FALSE
[zed_wrapper-2] 1670603444.342223068 [zed2.zed_node] [INFO]  * OD min. confidence: 50
[zed_wrapper-2] 1670603444.342320446 [zed2.zed_node] [INFO]  * OD prediction timeout [sec]: 0.5
[zed_wrapper-2] 1670603444.342404416 [zed2.zed_node] [INFO]  * OD tracking: TRUE
[zed_wrapper-2] 1670603444.342507747 [zed2.zed_node] [INFO]  * Object Detection model: 0 - MULTI CLASS BOX FAST
[zed_wrapper-2] 1670603444.342639750 [zed2.zed_node] [INFO]  * Object Filtering mode: 1 - NMS 3D
[zed_wrapper-2] 1670603444.342726088 [zed2.zed_node] [INFO]  * MultiClassBox people: TRUE
[zed_wrapper-2] 1670603444.342921389 [zed2.zed_node] [INFO]  * MultiClassBox vehicles: TRUE
[zed_wrapper-2] 1670603444.343056912 [zed2.zed_node] [INFO]  * MultiClassBox bags: TRUE
[zed_wrapper-2] 1670603444.343169875 [zed2.zed_node] [INFO]  * MultiClassBox animals: TRUE
[zed_wrapper-2] 1670603444.343256693 [zed2.zed_node] [INFO]  * MultiClassBox electronics: TRUE
[zed_wrapper-2] 1670603444.343356824 [zed2.zed_node] [INFO]  * MultiClassBox fruits and vegetables: TRUE
[zed_wrapper-2] 1670603444.343442586 [zed2.zed_node] [INFO]  * MultiClassBox sport-related objects: TRUE
[zed_wrapper-2] 1670603444.343538844 [zed2.zed_node] [INFO]  * Body format: 1 - POSE_34
[zed_wrapper-2] 1670603444.343595742 [zed2.zed_node] [INFO]  * Skeleton fitting: TRUE (forced by `object_detection.body_format`)
[zed_wrapper-2] 1670603444.343789090 [zed2.zed_node] [INFO]  * Obj. Det. QoS History: KEEP_LAST
[zed_wrapper-2] 1670603444.343882853 [zed2.zed_node] [INFO]  * Obj. Det. QoS History depth: 1
[zed_wrapper-2] 1670603444.343991239 [zed2.zed_node] [INFO]  * Obj. Det. QoS Reliability: RELIABLE
[zed_wrapper-2] 1670603444.344087273 [zed2.zed_node] [INFO]  * Obj. Det. QoS Durability: VOLATILE
[zed_wrapper-2] 1670603444.344353680 [zed2.zed_node] [INFO] *** SERVICES ***
[zed_wrapper-2] 1670603444.346661160 [zed2.zed_node] [INFO]  * '/zed2/zed_node/reset_odometry'
[zed_wrapper-2] 1670603444.347794308 [zed2.zed_node] [INFO]  * '/zed2/zed_node/reset_pos_tracking'
[zed_wrapper-2] 1670603444.350741356 [zed2.zed_node] [INFO]  * '/zed2/zed_node/set_pose'
[zed_wrapper-2] 1670603444.352093869 [zed2.zed_node] [INFO]  * '/zed2/zed_node/enable_obj_det'
[zed_wrapper-2] 1670603444.354214176 [zed2.zed_node] [INFO]  * '/zed2/zed_node/enable_mapping'
[zed_wrapper-2] 1670603444.355453279 [zed2.zed_node] [INFO]  * '/zed2/zed_node/start_svo_rec'
[zed_wrapper-2] 1670603444.356495320 [zed2.zed_node] [INFO]  * '/zed2/zed_node/stop_svo_rec'
[zed_wrapper-2] 1670603444.357457583 [zed2.zed_node] [INFO]  * '/zed2/zed_node/toggle_svo_pause'
[zed_wrapper-2] 1670603444.359528674 [zed2.zed_node] [INFO] ***** STARTING CAMERA *****
[zed_wrapper-2] 1670603444.359614468 [zed2.zed_node] [INFO] SDK Version: 3.8.2 - Build 63211_622b02a5
[zed_wrapper-2] 1670603444.367048217 [zed2.zed_node] [INFO] *** SVO OPENING ***
[zed_wrapper-2] [ZED][INFO] Logging level INFO
[zed_wrapper-2] 1670603445.296730713 [zed2.zed_node] [WARN] Error opening SVO: INVALID SVO FILE
[zed_wrapper-2] [ZED][ERROR] [Init]  Cannot load SVO file. Check that the path of the SVO is correct, avoid white spaces in filename, add ".svo" extension to filename.
[ERROR] [zed_wrapper-2]: process has died [pid 33463, exit code 1, cmd '/home/ubm/zed2ws/install/zed_wrapper/lib/zed_wrapper/zed_wrapper --ros-args -r __node:=zed_node -r __ns:=/zed2 --params-file /home/ubm/zed2ws/install/zed_wrapper/share/zed_wrapper/config/common.yaml --params-file /home/ubm/zed2ws/install/zed_wrapper/share/zed_wrapper/config/zed2.yaml --params-file /tmp/launch_params_jqayj4cl'].

**Comment by Myzhar** [comment]
@PallottaEnrico I'm sorry, `svo_path:='live'`, without the capital 'L' letter

**Comment by PallottaEnrico** [comment]
@Myzhar works now, thank you!

**Comment by Myzhar** [comment]
I'm sorry for the caused inconvenience, we will fix the launch file as soon as possible
