### ISSUE TITLE
Not supported on ROS2 galactic

### ISSUE THREAD

**Issue by GiteZz** [stereolabs/zed-ros2-wrapper#74]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

The provided code is not supported in ROS2 galactic due to using `set_on_parameters_set_callback` which was depricated in ROS2 foxy and removed in galactic. Removing this line avoid the problem and makes it possible to compile in galactic.

Switching to ROS foxy is not possible due to the bug with copying large arrays: https://github.com/ros2/rosidl_python/pull/129 . As everything seems to be kept up to date (cuda versions etc) it seems disappointing that the latest ROS version is not supported.

### Steps to Reproduce

1. Compile code in ROS galactic instead of ROS foxy

### Expected Result

Succes. 

### Actual Result

```
stderr: zed_components                               
/workspaces/zed/ZED/ROS/src/zed_components/src/zed_camera/src/zed_camera_component.cpp: In member function ‘void stereolabs::ZedCamera::initParameters()’:
/workspaces/zed/ZED/ROS/src/zed_components/src/zed_camera/src/zed_camera_component.cpp:263:5: error: ‘set_on_parameters_set_callback’ was not declared in this scope
  263 |     set_on_parameters_set_callback(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/ros/galactic/include/rclcpp/client.hpp:40,
                 from /opt/ros/galactic/include/rclcpp/callback_group.hpp:23,
                 from /opt/ros/galactic/include/rclcpp/any_executable.hpp:20,
                 from /opt/ros/galactic/include/rclcpp/memory_strategy.hpp:25,
                 from /opt/ros/galactic/include/rclcpp/memory_strategies.hpp:18,
                 from /opt/ros/galactic/include/rclcpp/executor_options.hpp:20,
                 from /opt/ros/galactic/include/rclcpp/executor.hpp:36,
                 from /opt/ros/galactic/include/rclcpp/executors/multi_threaded_executor.hpp:26,
                 from /opt/ros/galactic/include/rclcpp/executors.hpp:21,
                 from /opt/ros/galactic/include/rclcpp/rclcpp.hpp:156,
                 from /workspaces/zed/ZED/ROS/src/zed_components/src/zed_camera/include/zed_camera_component.hpp:31,
                 from /workspaces/zed/ZED/ROS/src/zed_components/src/zed_camera/src/zed_camera_component.cpp:25:
```

### ZED Camera model

ZED2i

### Environment

```shell
ROS galactic 
nvidia/cuda:11.4.1-cudnn8-devel-ubuntu20.04 docker on ubuntu:20.04 host OS
```

**Comment by Myzhar** [comment]
ROS Galactic is not yet officially supported by the ZED ROS2 wrapper because it's not an LTS version.
However, we noted the problem with "set_on_parameters_set_callback" and we will try to fix it without breaking the dynamic parameters feature.

**Comment by tlpss** [comment]
I would also like to use the wrapper on galactic @Myzhar, at least until the new Humble LTS is separated from the rolling releases. Would be awesome if this would be supported!

**Comment by tlpss** [comment]
At first glance, I believe it might be as simple as changing to the "add_on_parameters_set_callback". See [rclcpp ref](https://docs.ros2.org/latest/api/rclcpp/classrclcpp_1_1Node.html#a12d535bced9f26b65c0a450e6f40aff8). Tis function only allows for one callback to be registered, but I believe this is the case on the ZED component.

**Comment by Myzhar** [comment]
@tlpss I replaced the deprecated function in c9fba522a013e3ca8823dff9d544368ad599d00d
Can you check if this solves your problem and close the issue if it does?

**Comment by an99990** [comment]
hi @Myzhar i was able to build on galactic with your recent changes :)

**Comment by an99990** [comment]
however i try running it and i got this : 
```
root@96efae136e03:/opt/home/halodi_ws/src# ros2 launch zed_wrapper zed2.launch.py svo_path:=/home/halodi/ccw2.svo
^CTraceback (most recent call last):
  File "/opt/ros/galactic/install/bin/ros2", line 10, in <module>
    from importlib.metadata import distribution
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/galactic/install/bin/ros2", line 13, in <module>
    from importlib_metadata import distribution
  File "/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py", line 4, in <module>
    import csv
  File "/usr/lib/python3.6/csv.py", line 7, in <module>
    from _csv import Error, __version__, writer, reader, register_dialect, \
KeyboardInterrupt
root@96efae136e03:/opt/home/halodi_ws/src# ros2 launch root@96efae136e03:/opt/home/halodi_ws/src# ros2 launch root@96efae136e03:/opt/home/halodi_ws/src# ros2 launch zed_wrapper zed2.launch.py svo_path= /Downlo^C
root@96efae136e03:/opt/home/halodi_ws/src# ros2 launch zed_wrapper zed2.launch.py svo_path:=/opt/home/Downloads/cw2.svo 
[INFO] [launch]: All log files can be found below /root/.ros/log/2022-02-24-19-47-25-965016-96efae136e03-10381
[INFO] [launch]: Default logging verbosity is set to INFO
```

**Comment by an99990** [comment]
after installing importlib.metadata
```
[INFO] [launch]: All log files can be found below /root/.ros/log/2022-02-24-19-55-30-457901-96efae136e03-10402
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished coro=<LaunchService._process_one_event() done, defined at /opt/ros/galactic/install/lib/python3.6/site-packages/launch/launch_service.py:226> exception=SubstitutionFailure("file not found: [Errno 2] No such file or directory: 'xacro': 'xacro'",)>
Traceback (most recent call last):
  File "/opt/ros/galactic/install/lib/python3.6/site-packages/launch/substitutions/command.py", line 112, in perform
    universal_newlines=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xacro': 'xacro'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/ros/galactic/install/lib/python3.6/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/galactic/install/lib/python3.6/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/galactic/install/lib/python3.6/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/galactic/install/lib/python3.6/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/galactic/install/lib/python3.6/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  [Previous line repeated 3 more times]
  File "/opt/ros/galactic/install/lib/python3.6/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/galactic/install/lib/python3.6/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/galactic/install/lib/python3.6/site-packages/launch_ros/actions/node.py", line 465, in execute
    self._perform_substitutions(context)
  File "/opt/ros/galactic/install/lib/python3.6/site-packages/launch_ros/actions/node.py", line 420, in _perform_substitutions
    evaluated_parameters = evaluate_parameters(context, self.__parameters)
  File "/opt/ros/galactic/install/lib/python3.6/site-packages/launch_ros/utilities/evaluate_parameters.py", line 151, in evaluate_parameters
    output_params.append(evaluate_parameter_dict(context, param))
  File "/opt/ros/galactic/install/lib/python3.6/site-packages/launch_ros/utilities/evaluate_parameters.py", line 72, in evaluate_parameter_dict
    evaluated_value = perform_substitutions(context, list(value))
  File "/opt/ros/galactic/install/lib/python3.6/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in perform_substitutions
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/galactic/install/lib/python3.6/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in <listcomp>
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/galactic/install/lib/python3.6/site-packages/launch/launch_context.py", line 197, in perform_substitution
    return substitution.perform(self)
  File "/opt/ros/galactic/install/lib/python3.6/site-packages/launch/substitutions/command.py", line 114, in perform
    raise SubstitutionFailure(f'file not found: {ex}')
launch.substitutions.substitution_failure.SubstitutionFailure: file not found: [Errno 2] No such file or directory: 'xacro': 'xacro'
```

**Comment by Myzhar** [comment]
You miss the `xacro` package

**Comment by an99990** [comment]
how do i install it ? is it not in ros galactic ?

**Comment by an99990** [comment]
after installing xacro from source i got this error

```
root@96efae136e03:/opt/home/halodi_ws# ros2 launch zed_wrapper zed2.launch.py svo_path:=/opt/home/Downloads/cw2.svo 
[INFO] [launch]: All log files can be found below /root/.ros/log/2022-02-24-20-27-40-857287-96efae136e03-12039
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_state_publisher-1]: process started with pid [12043]
[INFO] [zed_wrapper-2]: process started with pid [12044]
[zed_wrapper-2] 1645734486.086887502 [zed2.zed_node] [INFO] ********************************
[zed_wrapper-2] 1645734486.087594578 [zed2.zed_node] [INFO]       ZED Camera Component 
[zed_wrapper-2] 1645734486.087711731 [zed2.zed_node] [INFO] ********************************
[zed_wrapper-2] 1645734486.087801811 [zed2.zed_node] [INFO]  * namespace: /zed2
[zed_wrapper-2] 1645734486.087890132 [zed2.zed_node] [INFO]  * node name: zed_node
[zed_wrapper-2] 1645734486.087999412 [zed2.zed_node] [INFO] ********************************
[zed_wrapper-2] 1645734486.088280342 [zed2.zed_node] [INFO] *** DEBUG parameters ***
[zed_wrapper-2] 1645734486.089389212 [zed2.zed_node] [INFO]  * Debug mode: FALSE
[zed_wrapper-2] 1645734486.089617341 [zed2.zed_node] [INFO] *** GENERAL parameters ***
[zed_wrapper-2] 1645734486.090269089 [zed2.zed_node] [INFO]  * Camera model: zed2 - ZED 2
[zed_wrapper-2] 1645734486.090915780 [zed2.zed_node] [INFO]  * SDK Verbose: 1
[zed_wrapper-2] 1645734486.091453351 [zed2.zed_node] [INFO]  * SVO: /opt/home/Downloads/cw2.svo
[zed_wrapper-2] 1645734486.092027562 [zed2.zed_node] [INFO]  * SVO Loop: TRUE
[zed_wrapper-2] 1645734486.092485453 [zed2.zed_node] [INFO]  * SVO Realtime: TRUE
[zed_wrapper-2] 1645734486.093039088 [zed2.zed_node] [INFO]  * Camera name: zed2
[zed_wrapper-2] 1645734486.093490354 [zed2.zed_node] [INFO]  * Camera ID: 0
[zed_wrapper-2] 1645734486.093923797 [zed2.zed_node] [INFO]  * Camera SN: 0
[zed_wrapper-2] 1645734486.094441400 [zed2.zed_node] [INFO]  * Camera timeout [sec]: 5
[zed_wrapper-2] 1645734486.094942746 [zed2.zed_node] [INFO]  * Camera reconnection temptatives: 5
[zed_wrapper-2] 1645734486.095352445 [zed2.zed_node] [INFO]  * Camera framerate: 30
[zed_wrapper-2] 1645734486.095896800 [zed2.zed_node] [INFO]  * GPU ID: -1
[zed_wrapper-2] 1645734486.096343682 [zed2.zed_node] [INFO]  * Camera resolution: 2 - HD720
[zed_wrapper-2] 1645734486.096736804 [zed2.zed_node] [INFO]  * Camera self calibration: TRUE
[zed_wrapper-2] 1645734486.097176359 [zed2.zed_node] [INFO]  * Camera flip: FALSE
[zed_wrapper-2] 1645734486.097583401 [zed2.zed_node] [INFO]  * [DYN] Publish framerate [Hz]: 15 
[zed_wrapper-2] 1645734486.097704937 [zed2.zed_node] [INFO] *** VIDEO parameters ***
[zed_wrapper-2] 1645734486.098104716 [zed2.zed_node] [INFO]  * Use old extrinsic parameters: 0
[zed_wrapper-2] 1645734486.098537774 [zed2.zed_node] [INFO]  * [DYN] Image downsample factor: 1 
[zed_wrapper-2] 1645734486.098942480 [zed2.zed_node] [INFO]  * [DYN] Brightness: 4
[zed_wrapper-2] 1645734486.099389043 [zed2.zed_node] [INFO]  * [DYN] Contrast: 4
[zed_wrapper-2] 1645734486.099904661 [zed2.zed_node] [INFO]  * [DYN] Hue: 0
[zed_wrapper-2] 1645734486.100348952 [zed2.zed_node] [INFO]  * [DYN] Saturation: 4
[zed_wrapper-2] 1645734486.100752794 [zed2.zed_node] [INFO]  * [DYN] Sharpness: 4
[zed_wrapper-2] 1645734486.101166396 [zed2.zed_node] [INFO]  * [DYN] Gamma: 8
[zed_wrapper-2] 1645734486.101606207 [zed2.zed_node] [INFO]  * [DYN] Auto Exposure/Gain: TRUE
[zed_wrapper-2] 1645734486.102069889 [zed2.zed_node] [INFO]  * [DYN] Exposure: 80
[zed_wrapper-2] 1645734486.102499044 [zed2.zed_node] [INFO]  * [DYN] Gain: 80
[zed_wrapper-2] 1645734486.102902022 [zed2.zed_node] [INFO]  * [DYN] Auto White Balance: TRUE
[zed_wrapper-2] 1645734486.103304296 [zed2.zed_node] [INFO]  * [DYN] White Balance Temperature: 42
[zed_wrapper-2] 1645734486.103809451 [zed2.zed_node] [INFO]  * Video QoS History: KEEP_LAST
[zed_wrapper-2] 1645734486.104220781 [zed2.zed_node] [INFO]  * Video QoS History depth: 1
[zed_wrapper-2] 1645734486.104648271 [zed2.zed_node] [INFO]  * Video QoS Reliability: RELIABLE
[zed_wrapper-2] 1645734486.105038801 [zed2.zed_node] [INFO]  * Video QoS Durability: VOLATILE
[zed_wrapper-2] 1645734486.105163570 [zed2.zed_node] [INFO] *** DEPTH parameters ***
[zed_wrapper-2] 1645734486.105606932 [zed2.zed_node] [INFO]  * Depth quality: 3 - ULTRA
[zed_wrapper-2] 1645734486.106004343 [zed2.zed_node] [INFO]  * Depth downsample factor: 1 
[zed_wrapper-2] 1645734486.106734843 [zed2.zed_node] [INFO]  * Min depth [m]: 0.2
[zed_wrapper-2] 1645734486.107304574 [zed2.zed_node] [INFO]  * Max depth [m]: 12
[zed_wrapper-2] 1645734486.107845537 [zed2.zed_node] [INFO]  * Depth Sensing Mode: 0 - STANDARD
[zed_wrapper-2] 1645734486.108280995 [zed2.zed_node] [INFO]  * Depth Stabilization: FALSE
[zed_wrapper-2] 1645734486.108740294 [zed2.zed_node] [INFO]  * OpenNI mode (16bit point cloud): FALSE
[zed_wrapper-2] 1645734486.109177864 [zed2.zed_node] [INFO]  * [DYN] Point cloud rate [Hz]: 10
[zed_wrapper-2] 1645734486.109589034 [zed2.zed_node] [INFO]  * [DYN] Depth Confidence: 75
[zed_wrapper-2] 1645734486.110062349 [zed2.zed_node] [INFO]  * [DYN] Depth Texture Confidence: 100
[zed_wrapper-2] 1645734486.110478255 [zed2.zed_node] [INFO]  * Depth QoS History: KEEP_LAST
[zed_wrapper-2] 1645734486.110872337 [zed2.zed_node] [INFO]  * Depth QoS History depth: 1
[zed_wrapper-2] 1645734486.111325876 [zed2.zed_node] [INFO]  * Depth QoS Reliability: RELIABLE
[zed_wrapper-2] 1645734486.111781142 [zed2.zed_node] [INFO]  * Depth QoS Durability: VOLATILE
[zed_wrapper-2] 1645734486.111989495 [zed2.zed_node] [INFO] *** POSITIONAL TRACKING parameters ***
[zed_wrapper-2] 1645734486.112408762 [zed2.zed_node] [INFO]  * Positional tracking enabled: FALSE
[zed_wrapper-2] 1645734486.113964610 [zed2.zed_node] [INFO]  * Base frame id: zed2_camera_center
[zed_wrapper-2] 1645734486.114404932 [zed2.zed_node] [INFO]  * Map frame id: map
[zed_wrapper-2] 1645734486.114818567 [zed2.zed_node] [INFO]  * Odometry frame id: odom
[zed_wrapper-2] 1645734486.115271945 [zed2.zed_node] [INFO]  * Broadcast Odometry TF: FALSE
[zed_wrapper-2] 1645734486.115751052 [zed2.zed_node] [INFO]  * [DYN] Path publishing rate: 2
[zed_wrapper-2] 1645734486.116185294 [zed2.zed_node] [INFO]  * Path history lenght: -1
[zed_wrapper-2] 1645734486.116646737 [zed2.zed_node] [INFO]  * Initial pose: [0,0,0,0,0,0,]
[zed_wrapper-2] 1645734486.117125907 [zed2.zed_node] [INFO]  * Area Memory: TRUE
[zed_wrapper-2] 1645734486.117511637 [zed2.zed_node] [INFO]  * Area Memory DB: 
[zed_wrapper-2] 1645734486.117887703 [zed2.zed_node] [INFO]  * IMU Fusion [not for ZED]: TRUE
[zed_wrapper-2] 1645734486.118348890 [zed2.zed_node] [INFO]  * Floor Alignment: TRUE
[zed_wrapper-2] 1645734486.118770012 [zed2.zed_node] [INFO]  * Init Odometry with first valid pose data: TRUE
[zed_wrapper-2] 1645734486.119198975 [zed2.zed_node] [INFO]  * 2D mode: FALSE
[zed_wrapper-2] 1645734486.119689569 [zed2.zed_node] [INFO]  * Pose/Odometry QoS History: KEEP_LAST
[zed_wrapper-2] 1645734486.120117860 [zed2.zed_node] [INFO]  * Pose/Odometry QoS History depth: 1
[zed_wrapper-2] 1645734486.120502502 [zed2.zed_node] [INFO]  * Pose/Odometry QoS Reliability: RELIABLE
[zed_wrapper-2] 1645734486.120908712 [zed2.zed_node] [INFO]  * Pose/Odometry QoS Durability: VOLATILE
[zed_wrapper-2] 1645734486.121025833 [zed2.zed_node] [INFO] *** SENSORS STACK parameters ***
[zed_wrapper-2] 1645734486.121478571 [zed2.zed_node] [INFO]  * Sensors Camera Sync: FALSE
[zed_wrapper-2] 1645734486.121895693 [zed2.zed_node] [INFO]  * Sensors publishing rate: 200 Hz
[zed_wrapper-2] 1645734486.122304528 [zed2.zed_node] [INFO]  * Sensors QoS History: KEEP_LAST
[zed_wrapper-2] 1645734486.122714450 [zed2.zed_node] [INFO]  * Sensors QoS History depth: 1
[zed_wrapper-2] 1645734486.123088276 [zed2.zed_node] [INFO]  * Sensors QoS Reliability: RELIABLE
[zed_wrapper-2] 1645734486.123483606 [zed2.zed_node] [INFO]  * Sensors QoS Durability: VOLATILE
[zed_wrapper-2] 1645734486.123646423 [zed2.zed_node] [INFO] *** Spatial Mapping parameters ***
[zed_wrapper-2] 1645734486.124089721 [zed2.zed_node] [INFO]  * Spatial Mapping Enabled: FALSE
[zed_wrapper-2] 1645734486.124559036 [zed2.zed_node] [INFO]  * Spatial Mapping resolution [m]: 0.03
[zed_wrapper-2] 1645734486.124999262 [zed2.zed_node] [INFO]  * 3D Max Mapping range [m]: 5
[zed_wrapper-2] 1645734486.125413985 [zed2.zed_node] [INFO]  * Map publishing rate [Hz]: 0.5
[zed_wrapper-2] 1645734486.125796419 [zed2.zed_node] [INFO]  * Sensors QoS History: KEEP_LAST
[zed_wrapper-2] 1645734486.126232485 [zed2.zed_node] [INFO]  * Sensors QoS History depth: 1
[zed_wrapper-2] 1645734486.126658055 [zed2.zed_node] [INFO]  * Sensors QoS Reliability: RELIABLE
[zed_wrapper-2] 1645734486.127042665 [zed2.zed_node] [INFO]  * Sensors QoS Durability: VOLATILE
[zed_wrapper-2] 1645734486.127173386 [zed2.zed_node] [INFO] *** OBJECT DETECTION parameters ***
[zed_wrapper-2] 1645734486.127622733 [zed2.zed_node] [INFO]  * Object Detection enabled: FALSE
[zed_wrapper-2] 1645734486.128044975 [zed2.zed_node] [INFO]  * OD min. confidence: 50
[zed_wrapper-2] 1645734486.128505041 [zed2.zed_node] [INFO]  * OD tracking: TRUE
[zed_wrapper-2] 1645734486.128920340 [zed2.zed_node] [INFO]  * Object Detection model: 3 - HUMAN BODY ACCURATE
[zed_wrapper-2] 1645734486.129366262 [zed2.zed_node] [INFO]  * MultiClassBox people: TRUE
[zed_wrapper-2] 1645734486.129807000 [zed2.zed_node] [INFO]  * MultiClassBox vehicles: TRUE
[zed_wrapper-2] 1645734486.130227867 [zed2.zed_node] [INFO]  * MultiClassBox bags: FALSE
[zed_wrapper-2] 1645734486.130632317 [zed2.zed_node] [INFO]  * MultiClassBox animals: FALSE
[zed_wrapper-2] 1645734486.131024703 [zed2.zed_node] [INFO]  * MultiClassBox electronics: FALSE
[zed_wrapper-2] 1645734486.131442529 [zed2.zed_node] [INFO]  * MultiClassBox fruits and vegetables: FALSE
[zed_wrapper-2] 1645734486.131924356 [zed2.zed_node] [INFO]  * Skeleton fitting: FALSE
[zed_wrapper-2] 1645734486.132344038 [zed2.zed_node] [INFO]  * Body format: 1
[zed_wrapper-2] 1645734486.132764073 [zed2.zed_node] [INFO]  * Obj. Det. QoS History: KEEP_LAST
[zed_wrapper-2] 1645734486.133182923 [zed2.zed_node] [INFO]  * Obj. Det. QoS History depth: 2
[zed_wrapper-2] 1645734486.133563725 [zed2.zed_node] [INFO]  * Obj. Det. QoS Reliability: BEST_EFFORT
[zed_wrapper-2] 1645734486.133977647 [zed2.zed_node] [INFO]  * Obj. Det. QoS Durability: VOLATILE
[zed_wrapper-2] 1645734486.134343185 [zed2.zed_node] [INFO] *** SERVICES ***
[zed_wrapper-2] 1645734486.138219270 [zed2.zed_node] [INFO]  * '/zed2/zed_node/reset_odometry'
[zed_wrapper-2] 1645734486.139840879 [zed2.zed_node] [INFO]  * '/zed2/zed_node/reset_pos_tracking'
[zed_wrapper-2] 1645734486.143050433 [zed2.zed_node] [INFO]  * '/zed2/zed_node/set_pose'
[zed_wrapper-2] 1645734486.145284077 [zed2.zed_node] [INFO]  * '/zed2/zed_node/enable_obj_det'
[zed_wrapper-2] 1645734486.146811765 [zed2.zed_node] [INFO]  * '/zed2/zed_node/enable_mapping'
[zed_wrapper-2] 1645734486.148698752 [zed2.zed_node] [INFO]  * '/zed2/zed_node/start_svo_rec'
[zed_wrapper-2] 1645734486.149970662 [zed2.zed_node] [INFO]  * '/zed2/zed_node/stop_svo_rec'
[zed_wrapper-2] 1645734486.151369198 [zed2.zed_node] [INFO]  * '/zed2/zed_node/toggle_svo_pause'
[zed_wrapper-2] 1645734486.151483983 [zed2.zed_node] [INFO] ***** STARTING CAMERA *****
[zed_wrapper-2] 1645734486.151639824 [zed2.zed_node] [INFO] SDK Version: 3.6.5 - Build 40028_a4a7e2b9
[zed_wrapper-2] 1645734486.250200201 [zed2.zed_node] [INFO] Parameter change callback
[zed_wrapper-2] 1645734486.250471147 [zed2.zed_node] [WARN] qos_overrides./tf.publisher.durability is not a dynamic parameter
[zed_wrapper-2] terminate called after throwing an instance of 'rclcpp::exceptions::InvalidParameterValueException'
[zed_wrapper-2]   what():  parameter 'qos_overrides./tf.publisher.durability' could not be set: qos_overrides./tf.publisher.durability is not a dynamic parameter
[robot_state_publisher-1] Error:   link 'zed2_camera_center' is not unique.
[robot_state_publisher-1]          at line 134 in /opt/ros/galactic/src/urdfdom/urdf_parser/src/model.cpp
[robot_state_publisher-1] Failed to parse robot description using: urdf_xml_parser/URDFXMLParser
[robot_state_publisher-1] terminate called after throwing an instance of 'std::runtime_error'
[robot_state_publisher-1]   what():  Unable to initialize urdf::model from robot description
[ERROR] [robot_state_publisher-1]: process has died [pid 12043, exit code -6, cmd '/opt/ros/galactic/install/lib/robot_state_publisher/robot_state_publisher --ros-args -r __node:=zed_state_publisher -r __ns:=/zed2 --params-file /tmp/launch_params_nig0khrm'].
[ERROR] [zed_wrapper-2]: process has died [pid 12044, exit code -6, cmd '/opt/home/halodi_ws/install/zed_wrapper/lib/zed_wrapper/zed_wrapper --ros-args -r __node:=zed_node -r __ns:=/zed2 --params-file /opt/home/halodi_ws/install/zed_wrapper/share/zed_wrapper/config/common.yaml --params-file /opt/home/halodi_ws/install/zed_wrapper/share/zed_wrapper/config/zed2.yaml --params-file /tmp/launch_params_3iwhutrf'].


```

**Comment by Myzhar** [comment]
The documentation exists, so I suppose it's available:
https://docs.ros.org/en/galactic/Tutorials/URDF/Using-Xacro-to-Clean-Up-a-URDF-File.html
Have you tried with
`sudo apt install ros-galactic-xacro`

**Comment by an99990** [comment]
thank you for your answer, it wasnt available in my ros docker. so i installed it with source.
